name: Monitor precio vuelo Sky

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium --with-deps

      # ⬇️ DESCARGAR ESTADO ANTERIOR
      - name: Download state
        uses: actions/download-artifact@v4
        with:
          name: estado-precio
        continue-on-error: true

      # ▶️ EJECUTAR SCRIPT
      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
        run: python main.py

      # ⬆️ GUARDAR ESTADO PARA EL SIGUIENTE RUN
      - name: Upload state
        uses: actions/upload-artifact@v4
        with:
          name: estado-precio
          path: |
            precio.txt
            aviso_oferta.txt
            sandbox_time.txt
